image:https://circleci.com/gh/feedhenry/mobile-security-android-template.svg?style=svg["CircleCI", link="https://circleci.com/gh/feedhenry/mobile-security-android-template"]
image:https://img.shields.io/badge/API-19%2B-brightgreen.svg?style=flat["API", link="https://android-arsenal.com/api?level=19"]
image:https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp/badge.svg?style=svg["Known Vulnerabilities", link="https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp"]

= Secure Native Android Template

A Native Android Application that demonstrates Secure Mobile Development Practises.

For more information, please check the https://github.com/feedhenry/mobile-security[Mobile Security Project].

== Binary Scanning with Kryptowire

Everytime when a PR is merged to master, the build script will automatically push the built binary to Kryptowire for security scanning.

== Features
- OpenID Connect Authentication
- Mobile Access Control
- Client Cert Authentication
- Certificate Pinning
- Code Obfuscation (with Proguard)
- Secure Data Storage
- Device Trust Checks (Root Access, Emulator Access, latest OS etc)
- 2FA with OTP (via Keycloak)
- Authentication Brute Force Detection (via Keycloak)
- Account Lockout Policies (via Keycloak)
- Authentication/Access Control Auditing & Logging (via Keycloak)
- Authenticated Calls to Protected Endpoints (via Keycloak)

== Build Instructions

* Make sure the Android SDK and the required build tools are installed locally. Please check ./app/build.gradle[the build gradle] file for the require SDK version and build tools version.
* To run all the tests:
[source, bash]
----
./gradlew test connectedAndroidTest
----
* To build
[source, bash]
----
/gradlew assembleDebug
----
* To do release build (you will need to setup the signing credential):
[source, bash]
----
./gradlew aR
----
* To push the built binary to Kryptowire
[source, bash]
----
export KRYPTOWIRE_API_KEY=<PUT YOUR API KEY HERE>
./pushToKryptowire.sh
----
