<<<<<<< 3d6357868b163f1c0839af44996ea67f21703349
image:https://circleci.com/gh/feedhenry/mobile-security-android-template.svg?style=svg["CircleCI", link="https://circleci.com/gh/feedhenry/mobile-security-android-template"]

=======
>>>>>>> add openid connect auth
= Secure Native Android Template

A Native Android Application that demonstrates Secure Mobile Development Practises.

<<<<<<< 3d6357868b163f1c0839af44996ea67f21703349
For more information, please check [Mobile Secure Project](https://github.com/feedhenry/mobile-security).

== Requirements
* Minimum SDK Version: 15
=======
== Requirements
* Minimum SDK Version: 16
>>>>>>> add openid connect auth
* Target SDK Version: 25

== Structure
* *manifests/*
** *AndroidManifest.xml* _(App Permissions Declared)_
* *java/com.feedhenry.securenativeandroidtemplate/*
*** *MainActivity* _(Menu and Fragment Navigation Logic)_
**** Relates to:
*****  `res/layout/activity_main.xml` _(Menu system master)_
*****  `res/layout/content_area.xml` _(Content view for fragments)_
*****  `res/layout/menu_app_bar.xml` _(Top app bar)_
*****  `res/layout/menu_nav_header.xml` _Sidebar app menu header)_
*****  `res/menu/menu_sidebar_content.xml` _(Sidebar content menu)_
*** *HomeFragment*  _(Home screen view and logic)_
**** Relates to: `res/layout/fragment_home.xml`
*** *AuthenticationFragment*  _(Authentication view and logic)_
**** Relates to: `res/layout/fragment_authentication.xml`
*** *AuthenticationDetailsFragment*  _(Authentication user details view and logic)_
<<<<<<< 3d6357868b163f1c0839af44996ea67f21703349
**** Relates to: `res/layout/fragment_authentication_details.xml`

== Push to Kryptowire

If you need to push the built binary to [Kryptowire](https://www.kryptowire.com/) for scan, just create a git tag like `release-*`. This will trigger a build in CircleCI, which will push the built release binary to Kryptowire automatically.

```bash
git checkout master
git tag release-1.0.0 #change the release version based on the current release
git push origin --tags
```
=======
**** Relates to: `res/layout/fragment_authentication_details.xml`
>>>>>>> add openid connect auth
