image:https://circleci.com/gh/feedhenry/mobile-security-android-template.svg?style=svg["CircleCI", link="https://circleci.com/gh/feedhenry/mobile-security-android-template"]
image:https://img.shields.io/badge/API-19%2B-brightgreen.svg?style=flat["API", link="https://android-arsenal.com/api?level=19"]


= Secure Native Android Template

A Native Android Application that demonstrates Secure Mobile Development Practises.

For more information, please check the https://github.com/feedhenry/mobile-security[Mobile Security Project].

== Binary Scanning with Kryptowire

If you need to push the built binary to https://www.kryptowire.com/[Kryptowire] for a security scan, you can create a git tag like `release-*`. This will trigger a build in CircleCI, which will push the built release binary to the Kryptowire platform automatically.

```bash
git checkout master
git tag release-1.0.0 #change the release version based on the current release
git push origin --tags
```

== Dependency Check
image:https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp/badge.svg?style=svg["Known Vulnerabilities", link="https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp"]

The Apache HTTP client can be seen as both an API and an implementation. The OkHttp dependency doesn’t use the vulnerable implementation. 

* SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-30647 (CVE-2015-5262)- Not Affected
* SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-31517 (CWE-23) - Not Affected
* SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-30645 (CVE-2012-6153) - Not Affected
* SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-30644 (CVE-2011-1498) - Not Affected
* SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-30646 (CVE-2014-3577) - Not Affected
