image:https://circleci.com/gh/feedhenry/mobile-security-android-template.svg?style=svg["CircleCI", link="https://circleci.com/gh/feedhenry/mobile-security-android-template"]
image:https://img.shields.io/badge/API-19%2B-brightgreen.svg?style=flat["API", link="https://android-arsenal.com/api?level=19"]
image:https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp/badge.svg?style=svg["Known Vulnerabilities", link="https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp"]

= Secure Native Android Template

A Native Android Application that demonstrates Secure Mobile Development Practises.

For more information, please check the https://github.com/feedhenry/mobile-security[Mobile Security Project].

== Binary Scanning with Kryptowire

Everytime when a PR is merged to master, the build script will automatically push the built binary to Kryptowire for security scanning.

== Features
- OpenID Connect Authentication
- Mobile Access Control
- Client Cert Authentication
- Certificate Pinning
- Code Obfuscation (with Proguard)
- Secure Data Storage
- Device Trust Checks (Root Access, Emulator Access, latest OS etc)
- 2FA with OTP (via Keycloak)
- Authentication Brute Force Detection (via Keycloak)
- Account Lockout Policies (via Keycloak)
- Authentication/Access Control Auditing & Logging (via Keycloak)
- Authenticated Calls to Protected Endpoints (via Keycloak)

== Build Instructions

* Make sure the Android SDK and the required build tools are installed locally. Please check ./app/build.gradle[the build gradle] file for the require SDK version and build tools version.
* To run all the tests:
[source, bash]
----
./gradlew test connectedAndroidTest
----
* To build
[source, bash]
----
/gradlew assembleDebug
----
* To do release build (you will need to setup the signing credential):
[source, bash]
----
./gradlew aR
----
* To push the built binary to Kryptowire
[source, bash]
----
export KRYPTOWIRE_API_KEY=<PUT YOUR API KEY HERE>
./pushToKryptowire.sh
----

== Work with Different Backend Services

By default the app will use the backend services that are running on https://security.skunkhenry.com:8443[a dedicated OpenShift cluster] for demonstration purpose. 

You can also configure the app to run against different backend services:

1. Update the URLs in link:app/src/main/res/raw/app_config.json[app_config.json] file.
2. If you are using HTTPS, update the certificate pinning configuration in link:app/src/main/res/xml/network_security_config[network_security_config.xml] file

To generate the hash value of the certificate, you can use this command:
[source, bash]
----
openssl s_client -servername <hostname> -connect <hostname:port> | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
----

If you are using self-signed certificate, follow the instructions in the next section.

== Work with Self-signed Certificate

By default, the app will not work with self-signed certificate due to security reasons. However, to help with local development, you may need to support it.  Here are the steps you can follow:

1. Get the CA certificate of the server. You can use this command:
+
[source, bash]
----
openssl s_client -showcerts -connect host:port
---- 
+
It will print out the full certificate chain of the server and you should save the content of the root certificate into a file.

2. Add the CA certificate to the project. It should be placed in `app/src/main/res/raw`.

3. Update the `network_security_config.xml` file to add the extra trust anchor like this:
+
[source, xml]
----
<domain-config>
...
  <trust-anchors>
    <certificates src="@raw/ca"/>
  </trust-anchors>
...
</domain-config>
----        
+
The file name should match the name of the CA certificate file.
