image:https://img.shields.io/badge/API-21%2B-brightgreen.svg?style=flat["API", link="https://android-arsenal.com/api?level=19"]
image:https://snyk.io/test/github/aerogear/android-showcase-template/master%2Fapp/badge.svg?style=svg["Known Vulnerabilities", link="https://snyk.io/test/github/aerogear/android-showcase-template/master%2Fapp"]

= Secure Native Android Template

A Native Android Application that demonstrates Secure Mobile Development Practises.

For more information, please check the https://github.com/feedhenry/mobile-security[Mobile Security Project].

== Binary Scanning with Kryptowire

Everytime when a PR is merged to master, the build script will automatically push the built binary to Kryptowire for security scanning.

== Features
- OpenID Connect Authentication
- Mobile Access Control
- Client Cert Authentication
- Certificate Pinning
- Code Obfuscation (with Proguard)
- Secure Data Storage
- Device Trust Checks (Root Access, Emulator Access etc)
- 2FA with OTP (via Keycloak)
- Authentication Brute Force Detection (via Keycloak)
- Account Lockout Policies (via Keycloak)
- Authentication/Access Control Auditing & Logging (via Keycloak)
- Authenticated Calls to Protected Endpoints (via Keycloak)

== Build Instructions

=== Prerequisites
* Android SDK or Android Studio from https://developer.android.com/studio/index.html[Google].  Check link:./app/build.gradle[build.gradle] file for the require SDK version and build tools version.
* It's recommended to install the latest version of http://openjdk.java.net/install/index.html[OpenJDK].

* To run all the tests:
[source, bash]
----
./gradlew test connectedAndroidTest
----
* To build
[source, bash]
----
/gradlew assembleDebug
----
* To do release build (you will need to setup the signing credential):
[source, bash]
----
./gradlew aR
----
* To push the built binary to Kryptowire
[source, bash]
----
export KRYPTOWIRE_API_KEY=<PUT YOUR API KEY HERE>
./pushToKryptowire.sh
----

== Using a Published SDK

=== jcenter()

To use a published version of the SDK, add jcenter to the link:build.grade[build.gradle] file in the root directory of this project.

[source, groovy]
----
allprojects {
    repositories {
        jcenter() // <-- Add This line
        google()
    }
}
----

=== Reference the Dependencies

In the link:./app/build.gradle[build.gradle] file in the app directory, add the dependencies provided by the SDK.

----
dependencies {
    ...
    implementation 'org.aerogear:core:0.1.0-2018-09'
    implementation 'org.aerogear:auth:0.1.0-2018-09' // <- adjust to suit release version
}
----

A full list of releases can be viewed https://github.com/aerogear/aerogear-android-sdk/releases[here].

== Installing Local Build of SDK

Alternatively the SDK can be installed manually instead of using a published version.

=== Clone and build the library

[source, sh]
----
git clone https://github.com/aerogear/aerogear-android-sdk
cd aerogear-android-sdk
./gradlew install
----

It's possible to verify the install went well by checking the local maven repository:

----
ls ~/.m2/repository/org/aerogear

# Should output android-push android-core core android-auth auth unifiedpush
----

=== MavenLocal()

If the build of the SDK is from source, add mavenLocal() to the link:build.grade[build.gradle] file in the root directory of this project.

[source, groovy]
----
allprojects {
    repositories {
        mavenLocal() // <-- Add This line
        google()
        jcenter()
    }
}
----

=== Reference the Dependencies

In the link:./app/build.gradle[build.gradle] file in the app directory, add the dependencies provided by the SDK.

----
dependencies {
    ...
    implementation 'org.aerogear:core:5.0.0-SNAPSHOT'
    implementation 'org.aerogear:auth:5.0.0-SNAPSHOT' //If you are using IDM services provided by KeyCloak
}
----

== Work with Different Backend Services

By default the app will use the backend services that are running on https://security.skunkhenry.com:8443[a dedicated OpenShift cluster] for demonstration purpose. 

You can also configure the app to run against different backend services:

=== Keycloak Configuration
The Keycloak configuration is saved in the https://github.com/aerogear/android-showcase-template/tree/master/app/src/main/assets/mobile-services.json[mobile-services.json] file.

.Code
[source,json,linenums,indent=0]
....
include::https://raw.githubusercontent.com/aerogear/android-showcase-template/master/app/src/main/assets/mobile-services.json[]
....

=== Cert Pinning Configuration
If you are using HTTPS, update the certificate pinning configuration in link:app/src/main/res/xml/network_security_config.xml[network_security_config.xml] file

To generate the hash value of the certificate, you can use this command:
[source, bash]
----
openssl s_client -servername <hostname> -connect <hostname:port> | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
----

If you are using self-signed certificate, follow the instructions in the next section.

== Work with Self-signed Certificate

By default, the app will not work with self-signed certificate due to security reasons. However, to help with local development, you may need to support it.  Here are the steps you can follow:

1. Get the CA certificate of the server. You can use this command:
+
[source, bash]
----
openssl s_client -showcerts -connect host:port
---- 
+
It will print out the full certificate chain of the server and you should save the content of the root certificate into a file.

2. Add the CA certificate to the project. It should be placed in `app/src/main/res/raw`.

3. Update the `network_security_config.xml` file to add the extra trust anchor like this:
+
[source, xml]
----
<domain-config>
...
  <trust-anchors>
    <certificates src="@raw/ca"/>
  </trust-anchors>
...
</domain-config>
----        
+
The file name should match the name of the CA certificate file.
