image:https://circleci.com/gh/feedhenry/mobile-security-android-template.svg?style=svg["CircleCI", link="https://circleci.com/gh/feedhenry/mobile-security-android-template"]
image:https://img.shields.io/badge/API-19%2B-brightgreen.svg?style=flat["API", link="https://android-arsenal.com/api?level=19"]
image:https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp/badge.svg?style=svg["Known Vulnerabilities", link="https://snyk.io/test/github/feedhenry/mobile-security-android-template/master%2Fapp"]

= Secure Native Android Template

A Native Android Application that demonstrates Secure Mobile Development Practises.

For more information, please check the https://github.com/feedhenry/mobile-security[Mobile Security Project].

== Binary Scanning with Kryptowire

If you need to push the built binary to https://www.kryptowire.com/[Kryptowire] for a security scan, you can create a git tag like `release-*`. This will trigger a build in CircleCI, which will push the built release binary to the Kryptowire platform automatically.

```bash
git checkout master
git tag release-1.0.0 #change the release version based on the current release
git push origin --tags
```
== Features
- OpenID Connect Authentication
- Mobile Access Control
- Client Cert Authentication
- Certificate Pinning
- Code Obfuscation (with Proguard)
- Secure Data Storage
- Device Trust Checks (Root Access, Emulator Access, latest OS etc)
- 2FA with OTP (via Keycloak)
- Authentication Brute Force Detection (via Keycloak)
- Account Lockout Policies (via Keycloak)
- Authentication/Access Control Auditing & Logging (via Keycloak)
- Authenticated Calls to Protected Endpoints (via Keycloak)
