image:https://img.shields.io/badge/API-21%2B-brightgreen.svg?style=flat["API", link="https://android-arsenal.com/api?level=19"]
image:https://snyk.io/test/github/aerogear/android-showcase-template/master%2Fapp/badge.svg?style=svg["Known Vulnerabilities", link="https://snyk.io/test/github/aerogear/android-showcase-template/master%2Fapp"]

= Secure Native Android Template

A Native Android Application that demonstrates Secure Mobile Development Practises.

For more information, please check the https://github.com/feedhenry/mobile-security[Mobile Security Project].

== Binary Scanning with Kryptowire

Everytime when a PR is merged to master, the build script will automatically push the built binary to Kryptowire for security scanning.

== Features
- OpenID Connect Authentication
- Mobile Access Control
- Client Cert Authentication
- Certificate Pinning
- Code Obfuscation (with Proguard)
- Secure Data Storage
- Device Trust Checks (Root Access, Emulator Access etc)
- 2FA with OTP (via Keycloak)
- Authentication Brute Force Detection (via Keycloak)
- Account Lockout Policies (via Keycloak)
- Authentication/Access Control Auditing & Logging (via Keycloak)
- Authenticated Calls to Protected Endpoints (via Keycloak)

== Run Showcase
The `master` branch will always track to the latest release of the SDK.

To run the showcase app

[source, bash]
----
git clone git@github.com:aerogear/android-showcase-template.git
----

Open showcase app in Android Studio and select the build variant `release` or `debug` to run the showcase with the latest release, or select build variant `local` to run the show case with a locally installed version of the https://github.com/aerogear/aerogear-android-sdk/blob/master/docs/modules/ROOT/pages/index.adoc[SDK]

== Build Instructions

For full build instructions please take some time to read our link:./CONTRIBUTING.md[Contributing Guide]

== Work with Different Backend Services

By default the app will use the backend services that are running on https://security.skunkhenry.com:8443[a dedicated OpenShift cluster] for demonstration purpose. 

You can also configure the app to run against different backend services:

=== Keycloak Configuration
The Keycloak configuration is saved in the https://github.com/aerogear/android-showcase-template/tree/master/app/src/main/assets/mobile-services.json[mobile-services.json] file.

.Code
[source,json,linenums,indent=0]
....
include::https://raw.githubusercontent.com/aerogear/android-showcase-template/master/app/src/main/assets/mobile-services.json[]
....

== Work with Self-signed Certificate

By default, the app will not work with self-signed certificate due to security reasons. However, to help with local development, you may need to support it.  link:https://docs.aerogear.org/aerogear/latest/getting-started.html#using-self-signed-certificates-in-mobile-apps[Docs.aerogear.org] has full configuration instructions.